version: '3'

# declare our database as a service based on official postgres docker image
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
  # declare our api as a service based on our custom image
    platform: linux/amd64
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile

volumes:
# Volumes are memory of our docker containers. 
# If we want to keep our datas when we restart them, it’s necessary to use volumes.
  db:
    driver: local
    # declare volumes at the end of the file and store them in our device
